import 'package:dio/dio.dart';
import '../models/experience_model.dart';

class ApiService {
  final Dio _dio = Dio(
    BaseOptions(baseUrl: 'https://staging.chamberofsecrets.8club.co/v1'),
  );

  ApiService() {
    _dio.interceptors.add(LogInterceptor(
      request: true,
      requestBody: true,
      responseBody: true,
      responseHeader: false,
    ));
  }

  Future<Autogenerated> fetchExperiences() async {
    try {
      final response = await _dio.get('/experiences?active=true');

      if (response.statusCode == 200 && response.data != null) {
        final autogenerated = Autogenerated.fromJson(response.data);
        final experiences = autogenerated.data?.experiences;

        if (experiences != null && experiences.isNotEmpty) {
        } else {
          print("No experiences found.");
        }

        return autogenerated;
      } else {
        throw Exception("Failed to load experiences: ${response.statusCode} - ${response.statusMessage}");
      }
    } catch (e, stackTrace) {
      if (e is DioException) {
        print("DioError: ${e.response?.data ?? e.message}");
      } else {
        print("Unknown Error: $e");
      }
      print(stackTrace);
      throw Exception("API error: $e");
    }
  }
}
