class Autogenerated {
  final String message;
  final Data? data;

  Autogenerated({required this.message, this.data});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      message: json['message'] ?? '',
      data: json['data'] != null ? Data.fromJson(json['data']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> dataMap = {};
    dataMap['message'] = message;
    if (data != null) {
      dataMap['data'] = data!.toJson();
    }
    return dataMap;
  }
}

class Data {
  final List<Experiences> experiences;

  Data({required this.experiences});

  factory Data.fromJson(Map<String, dynamic> json) {
    final experiencesJson = json['experiences'] as List<dynamic>? ?? [];
    return Data(
      experiences: experiencesJson.map((v) => Experiences.fromJson(v)).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'experiences': experiences.map((v) => v.toJson()).toList(),
    };
  }
}

class Experiences {
  final int id;
  final String name;
  final String tagline;
  final String description;
  final String imageUrl;
  final String iconUrl;
  final int order;

  Experiences({
    required this.id,
    required this.name,
    required this.tagline,
    required this.description,
    required this.imageUrl,
    required this.iconUrl,
    required this.order,
  });

  factory Experiences.fromJson(Map<String, dynamic> json) {
    return Experiences(
      id: json['id'] ?? 0,
      name: json['name'] ?? '',
      tagline: json['tagline'] ?? '',
      description: json['description'] ?? '',
      imageUrl: json['image_url'] ?? '',
      iconUrl: json['icon_url'] ?? '',
      order: json['order'] ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'tagline': tagline,
      'description': description,
      'image_url': imageUrl,
      'icon_url': iconUrl,
      'order': order,
    };
  }
}
